import { Frett } from './frettir';
export const FRETTIR: Frett[] = [
    { id: 1, photo: '../../assets/frettir/car-driving-with-balloons.jpeg' , title: 'Lorem Ipsum Con', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam venenatis leo eu ligula condimentum, a porttitor turpis vehicula.', date: '09/09/09', category: 'Tækni', subcategories: ['Bílar', 'Elon Musk'] },
    { id: 2, photo: '../../assets/frettir/cars.jpeg' , title: 'Lorem Ipsum Con', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam venenatis leo eu ligula condimentum, a porttitor turpis vehicula.', date: '09/09/09', category: 'Viðskipti', subcategories: ['Bílar'] },
    { id: 3, photo: '../../assets/frettir/happy-halloween.jpeg' , title: 'Lorem Ipsum Con', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam venenatis leo eu ligula condimentum, a porttitor turpis vehicula.', date: '09/09/09', category: 'Listin', subcategories: ['Sálinn', 'Píratar', 'Jól'] },
    { id: 4, photo: '../../assets/frettir/man-surfing.jpeg' , title: 'Lorem Ipsum Con', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam venenatis leo eu ligula condimentum, a porttitor turpis vehicula.', date: '09/09/09', category: 'Heilsa', subcategories: ['Samfélag'] },
    { id: 5, photo: '../../assets/frettir/man-with-flag.jpeg' , title: 'Lorem Ipsum Con', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam venenatis leo eu ligula condimentum, a porttitor turpis vehicula.', date: '09/09/09', category: 'Heilsa', subcategories: ['Elon Musk', 'Sálinn'] },
    { id: 6, photo: '../../assets/frettir/man-with-guitar.jpeg' , title: 'Lorem Ipsum Con', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam venenatis leo eu ligula condimentum, a porttitor turpis vehicula.', date: '09/09/09', category: 'Listin', subcategories: ['Samfélag'] },
    { id: 7, photo: '../../assets/frettir/man-working.jpeg' , title: 'Lorem Ipsum Con', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam venenatis leo eu ligula condimentum, a porttitor turpis vehicula.', date: '09/09/09', category: 'Viðskipti', subcategories: ['Bílar', 'Hlutabréf'] },
    { id: 8, photo: '../../assets/frettir/people-with-dog.jpeg' , title: 'Lorem Ipsum Con', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam venenatis leo eu ligula condimentum, a porttitor turpis vehicula.', date: '09/09/09', category: 'Viðskipti', subcategories: ['Hlutabréf', 'Elon Musk'] },
    { id: 9, photo: '../../assets/frettir/woman-drinking-coffee.jpeg' , title: 'Lorem Ipsum Con', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam venenatis leo eu ligula condimentum, a porttitor turpis vehicula.', date: '09/09/09', category: 'Tækni', subcategories: ['Elon Musk', 'Bílar'] },
    { id: 10, photo: '../../assets/frettir/women-kissing.jpeg' , title: 'Lorem Ipsum Con', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam venenatis leo eu ligula condimentum, a porttitor turpis vehicula.', date: '09/09/09', category: 'Heilsa', subcategories: ['Bílar', 'Sálinn'] }
]
